### ISSUE TITLE
Add `tool-alias.yml` to Index Repository

### ISSUE THREAD

**Issue by keshav-space** [aboutcode-org/federatedcode#24]
The `tool-alias.yml` file should contain the mapping of alias to the purl for the corresponding tool. These alias are used for naming the output generated by these tools. For example, the package scan from scancode.io is named `scancodeio.json`.

`tool-alias.yml` would look like this:

```yaml
tools:
  scancodeio: pkg:github/scancode.io
  scancode-toolkit: pkg:github/scancode-toolkit
```
