### ISSUE TITLE
Advertise a pushed ScanCode scan in the FederatedCode ActivityPub server

### ISSUE THREAD

**Issue by keshav-space** [aboutcode-org/federatedcode#41]
A typical note for scan advertisement looks like:

```yml
purl: 'pkg:alpine/advancecomp@2.1-r2'
scans:
  - tool: 'pkg:pypi/scancode-toolkit'
    file_name: scancodeio.json
  - tool: 'pkg:type/namespace/name'
    file_name: tool_scan.json
```
